
stripe.secretKey=sk_test_51SmEzrHse2hHVesu6Mr2MgGkOySs3u0r0WZHdV49fEJK9hlJc0PQ0XMsMRCx3BBE9E4WYsm54spheKt059x3KsvQ00Yzbq6VEb

spring.application.name=paymentservice
server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/paymentdb
spring.datasource.username=root
spring.datasource.password=system

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
